server:
  port: 8081
spring:
  rabbit:
    host: localhost
    port: 5672
    username: guest
    password: guest
studyrabbit:
  rabbit:
    exchange: studyrabbit.exchange
    queue: studyrabbit.queue
    routingKey: study.routingkey